### ISSUE TITLE
Autoregressive generator doesn't work with initials provided

### ISSUE THREAD

**Issue by jpeg729** [matousc89/signalz#1]
Following your example...
```python
import numpy as np
import signalz
N = 1000
a = [-0.41, 1.27, -1.85, 1.79]
A = np.ones((N,4))
A = A*a
```
then I try
```python
initials = np.random.rand(4)
x = signalz.autoregressive_model(N, A, noise="white", initials=initials)
```
but I get
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mpage/miniconda3/lib/python3.6/site-packages/signalz/generators/autoregressive_model.py", line 124, in autoregressive_model
    raise ValueError('The length of initials values and a must agree.')
ValueError: The length of initials values and a must agree.
```
so I try
```python
initials = np.random.rand(1000)
x = signalz.autoregressive_model(N, A, noise="white", initials=initials)
```
but I get
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mpage/miniconda3/lib/python3.6/site-packages/signalz/generators/autoregressive_model.py", line 125, in autoregressive_model
    x[:taps] = initials
ValueError: could not broadcast input array from shape (1000) into shape (4)
```
Unless I am being particularly stupid I did what the first error told me to do, but that causes an error too.

**Comment by matousc89** [comment]
It was a bug. It seems to be fixed now. The following example should work:

```
import numpy as np
import signalz

N = 1000
a = [-0.41, 1.27, -1.85, 1.79]
A = np.ones((N,4))
A = A*a

initials = np.random.rand(4)
x = signalz.autoregressive_model(N, A, noise="white", initials=initials)
```
